function _precompile_()
    ccall(:jl_generating_output, Cint, ()) == 1 || return nothing
    precompile(Tuple{typeof(JSON.Parser.parse_object), JSON.Parser.ParserContext{DataStructures.OrderedDict{String, Any}, Int64}, JSON.Parser.MemoryParserState})
    precompile(Tuple{typeof(JSON.Parser.read_four_hex_digits!), JSON.Parser.MemoryParserState})
    precompile(Tuple{typeof(JSON.Parser.parse_array), JSON.Parser.ParserContext{DataStructures.OrderedDict{String, Any}, Int64}, JSON.Parser.MemoryParserState})
    precompile(Tuple{getfield(JSON.Parser, Symbol("#kw##parse")), Array{Any, 1}, typeof(JSON.Parser.parse), String})
    precompile(Tuple{getfield(JSON.Parser, Symbol("#kw##parsefile")), Array{Any, 1}, typeof(JSON.Parser.parsefile), String})
    precompile(Tuple{typeof(JSON.Parser.hasleadingzero), Array{UInt8, 1}, Int64, Int64})
    precompile(Tuple{typeof(JSON.Writer.show_json), JSON.Writer.CompactContext{Base.AbstractIOBuffer{Array{UInt8, 1}}}, JSON.Serializations.StandardSerialization, Tuple{Float64, Bool}})
    precompile(Tuple{typeof(JSON.Parser.parse_jsconstant), JSON.Parser.MemoryParserState})
    precompile(Tuple{typeof(JSON.Writer.show_json), JSON.Writer.CompactContext{Base.AbstractIOBuffer{Array{UInt8, 1}}}, JSON.Serializations.StandardSerialization, Tuple{Int64, Bool}})
    precompile(Tuple{typeof(JSON.Writer.show_json), JSON.Writer.CompactContext{Base.AbstractIOBuffer{Array{UInt8, 1}}}, JSON.Serializations.StandardSerialization, Base.Dict{String, Any}})
    precompile(Tuple{typeof(JSON.Parser._count_before), String, Char, Int64})
    precompile(Tuple{typeof(JSON.Writer.show_json), JSON.Writer.CompactContext{Base.AbstractIOBuffer{Array{UInt8, 1}}}, JSON.Serializations.StandardSerialization, JSON.Writer.CompositeTypeWrapper{QpcrAnalysis.TargetResultEle}})
    precompile(Tuple{typeof(JSON.Parser.isjsonspace), UInt8})
    precompile(Tuple{typeof(JSON.Parser.int_from_bytes), JSON.Parser.ParserContext{DataStructures.OrderedDict{String, Any}, Int64}, JSON.Parser.MemoryParserState, Array{UInt8, 1}, Int64, Int64})
    precompile(Tuple{typeof(JSON.Parser.skip!), JSON.Parser.MemoryParserState, UInt8, UInt8, UInt8})
    precompile(Tuple{typeof(JSON.Parser.read_unicode_escape!), JSON.Parser.MemoryParserState})
    precompile(Tuple{typeof(JSON.Writer.show_element), JSON.Writer.CompactContext{Base.AbstractIOBuffer{Array{UInt8, 1}}}, JSON.Serializations.StandardSerialization, Int64})
    precompile(Tuple{typeof(JSON.Parser.number_from_bytes), JSON.Parser.ParserContext{DataStructures.OrderedDict{String, Any}, Int64}, JSON.Parser.MemoryParserState, Bool, Array{UInt8, 1}, Int64, Int64})
    precompile(Tuple{typeof(JSON.Writer.show_element), JSON.Writer.CompactContext{Base.AbstractIOBuffer{Array{UInt8, 1}}}, JSON.Serializations.StandardSerialization, Float64})
    precompile(Tuple{typeof(JSON.Parser.parse_string), JSON.Parser.MemoryParserState, Array{UInt8, 1}})
    precompile(Tuple{typeof(JSON.Writer.print), Base.AbstractIOBuffer{Array{UInt8, 1}}, Base.Dict{String, Any}})
    precompile(Tuple{typeof(JSON.Writer.show_json), JSON.Writer.CompactContext{Base.AbstractIOBuffer{Array{UInt8, 1}}}, JSON.Serializations.StandardSerialization, Array{DataStructures.OrderedDict{K, V} where V where K, 1}})
    precompile(Tuple{typeof(JSON.Writer.show_element), JSON.Writer.CompactContext{Base.AbstractIOBuffer{Array{UInt8, 1}}}, JSON.Serializations.StandardSerialization, Bool})
    precompile(Tuple{typeof(JSON.Writer.print), Base.AbstractIOBuffer{Array{UInt8, 1}}, DataStructures.OrderedDict{String, Any}})
    precompile(Tuple{typeof(JSON.Writer.show_json), JSON.Writer.CompactContext{Base.AbstractIOBuffer{Array{UInt8, 1}}}, JSON.Serializations.StandardSerialization, Array{DataStructures.OrderedDict{String, Any}, 1}})
    precompile(Tuple{typeof(JSON.Writer.show_json), JSON.Writer.CompactContext{Base.AbstractIOBuffer{Array{UInt8, 1}}}, JSON.Serializations.StandardSerialization, String})
    precompile(Tuple{typeof(JSON.Writer.show_json), JSON.Writer.CompactContext{Base.AbstractIOBuffer{Array{UInt8, 1}}}, JSON.Serializations.StandardSerialization, Array{Any, 1}})
    precompile(Tuple{getfield(JSON.Parser, Symbol("##parsefile#3")), Type{(DataStructures.OrderedDict{K, V} where V) where K}, Type{Int64}, Bool, typeof(identity), String})
    precompile(Tuple{typeof(JSON.Writer.lower), QpcrAnalysis.TargetResultEle})
    precompile(Tuple{typeof(JSON.Parser.predict_string), JSON.Parser.MemoryParserState})
    precompile(Tuple{typeof(JSON.Writer.show_json), JSON.Writer.CompactContext{Base.AbstractIOBuffer{Array{UInt8, 1}}}, JSON.Serializations.StandardSerialization, Void})
    precompile(Tuple{typeof(JSON.Parser._error), String, JSON.Parser.MemoryParserState})
    precompile(Tuple{getfield(JSON.Writer, Symbol("##show_json#3")), Void, typeof(identity), Base.AbstractIOBuffer{Array{UInt8, 1}}, JSON.Serializations.StandardSerialization, Base.Dict{String, Any}})
    precompile(Tuple{getfield(JSON.Writer, Symbol("##show_json#3")), Void, typeof(identity), Base.AbstractIOBuffer{Array{UInt8, 1}}, JSON.Serializations.StandardSerialization, Array{Any, 1}})
    precompile(Tuple{typeof(JSON.Parser.parse_value), JSON.Parser.ParserContext{DataStructures.OrderedDict{String, Any}, Int64}, JSON.Parser.MemoryParserState})
    precompile(Tuple{typeof(JSON.Parser.parse_number), JSON.Parser.ParserContext{DataStructures.OrderedDict{String, Any}, Int64}, JSON.Parser.MemoryParserState})
    precompile(Tuple{typeof(JSON.Writer.print), Base.AbstractIOBuffer{Array{UInt8, 1}}, Array{Any, 1}})
    precompile(Tuple{typeof(JSON.Writer.show_pair), JSON.Writer.CompactContext{Base.AbstractIOBuffer{Array{UInt8, 1}}}, JSON.Serializations.StandardSerialization, Symbol, Float64})
    precompile(Tuple{typeof(JSON.Writer.show_key), JSON.Writer.CompactContext{Base.AbstractIOBuffer{Array{UInt8, 1}}}, Symbol})
    precompile(Tuple{typeof(JSON.Writer.show_key), JSON.Writer.CompactContext{Base.AbstractIOBuffer{Array{UInt8, 1}}}, String})
    precompile(Tuple{typeof(JSON.Writer.show_json), JSON.Writer.CompactContext{Base.AbstractIOBuffer{Array{UInt8, 1}}}, JSON.Serializations.StandardSerialization, Bool})
    precompile(Tuple{typeof(JSON.Writer.show_json), JSON.Writer.CompactContext{Base.AbstractIOBuffer{Array{UInt8, 1}}}, JSON.Serializations.StandardSerialization, DataStructures.OrderedDict{String, Any}})
    precompile(Tuple{typeof(JSON.Writer.show_json), JSON.Writer.CompactContext{Base.AbstractIOBuffer{Array{UInt8, 1}}}, JSON.Serializations.StandardSerialization, Float64})
    precompile(Tuple{getfield(JSON.Parser, Symbol("##parse#1")), Type{(DataStructures.OrderedDict{K, V} where V) where K}, Type{Int64}, typeof(identity), String})
    precompile(Tuple{typeof(JSON.Parser.parse_string), JSON.Parser.MemoryParserState})
    precompile(Tuple{typeof(JSON.Writer.show_pair), JSON.Writer.CompactContext{Base.AbstractIOBuffer{Array{UInt8, 1}}}, JSON.Serializations.StandardSerialization, Symbol, Int64})
    precompile(Tuple{getfield(JSON.Writer, Symbol("##show_json#3")), Void, typeof(identity), Base.AbstractIOBuffer{Array{UInt8, 1}}, JSON.Serializations.StandardSerialization, DataStructures.OrderedDict{String, Any}})
    precompile(Tuple{typeof(JSON.Writer.show_json), JSON.Writer.CompactContext{Base.AbstractIOBuffer{Array{UInt8, 1}}}, JSON.Serializations.StandardSerialization, Int64})
    precompile(Tuple{typeof(JSON.Writer.show_json), JSON.Writer.CompactContext{Base.AbstractIOBuffer{Array{UInt8, 1}}}, JSON.Serializations.StandardSerialization, QpcrAnalysis.TargetResultEle})
end
