function _precompile_()
    ccall(:jl_generating_output, Cint, ()) == 1 || return nothing
    precompile(Tuple{typeof(DataArrays.gen_na_conds), Symbol, Int64, Tuple{DataType, DataType}, Type{Int}, Array{Int64, 1}, Int64, Tuple{Bool, Bool}})
    precompile(Tuple{typeof(DataArrays.gen_na_conds), Symbol, Int64, Tuple{DataType, DataType}, Type{Int}, Array{Int64, 1}, Int64, Tuple{Bool}})
    precompile(Tuple{typeof(DataArrays.gen_na_conds), Symbol, Int64, Tuple{DataType, DataType, DataType, DataType}, Type{Int}, Array{Int64, 1}, Int64, Tuple{Bool}})
    precompile(Tuple{typeof(DataArrays.gen_na_conds), Symbol, Int64, Tuple{DataType, DataType, DataType, DataType}, Type{Int}, Array{Int64, 1}, Int64, Tuple{}})
    precompile(Tuple{typeof(DataArrays.gen_na_conds), Symbol, Int64, Tuple{DataType, DataType}, Type{Int}, Array{Int64, 1}, Int64, Tuple{}})
    precompile(Tuple{typeof(DataArrays._broadcast!), typeof(Base.:(*)), DataArrays.DataArray{Any, 1}, DataArrays.DataArray{Any, 1}, Array{Float64, 1}})
    precompile(Tuple{typeof(DataArrays._broadcast!), typeof(Base.:(-)), DataArrays.DataArray{Float64, 1}, DataArrays.DataArray{Float64, 1}, DataArrays.DataArray{Float64, 1}})
    precompile(Tuple{typeof(DataArrays._broadcast!), typeof(Base.:(+)), DataArrays.DataArray{Float64, 1}, DataArrays.DataArray{Float64, 1}, Float64})
    precompile(Tuple{typeof(DataArrays.myismissing), Base.Order.ForwardOrdering, Array{UInt64, 1}, Int64})
    precompile(Tuple{typeof(DataArrays._broadcast!), getfield(QpcrAnalysis, Symbol("##1398#1401")), DataArrays.DataArray{Any, 1}, Float64, DataArrays.DataArray{Any, 1}, Int64, Array{Float64, 1}})
    precompile(Tuple{typeof(DataArrays._broadcast!), typeof(Base.:(-)), DataArrays.DataArray{Any, 2}, DataArrays.DataArray{Float64, 2}, Base.LinAlg.RowVector{Any, Array{Any, 1}}})
    precompile(Tuple{getfield(DataArrays, Symbol("##103#110")), Int64})
    precompile(Tuple{typeof(DataArrays.unsafe_ismissing), DataArrays.DataArray{Any, 2}, Tuple{Array{Any, 2}, Array{UInt64, 1}}, Int64})
    precompile(Tuple{getfield(DataArrays, Symbol("##106#113")), Int64})
    precompile(Tuple{typeof(DataArrays.unsafe_ismissing), DataArrays.DataArray{Float64, 2}, Tuple{Array{Float64, 2}, Array{UInt64, 1}}, Int64})
    precompile(Tuple{typeof(DataArrays.missings2right!), DataArrays.DataArray{Float64, 1}, Base.Order.ForwardOrdering, Int64, Int64})
    precompile(Tuple{typeof(DataArrays.unsafe_ismissing), DataArrays.DataArray{Float64, 1}, Tuple{Array{Float64, 1}, Array{UInt64, 1}}, Int64})
    precompile(Tuple{typeof(DataArrays.broadcast_t), typeof(identity), Type{Any}, Tuple{Base.OneTo{Int64}}, DataArrays.DataArray{Any, 1}, Array{Float64, 1}, Array{Float64, 1}})
    precompile(Tuple{typeof(DataArrays.broadcast_t), typeof(identity), Type{Any}, Tuple{Base.OneTo{Int64}, Base.OneTo{Int64}}, DataArrays.DataArray{Float64, 2}, Base.LinAlg.RowVector{Any, Array{Any, 1}}, Base.LinAlg.RowVector{Any, Array{Any, 1}}})
    precompile(Tuple{typeof(DataArrays.broadcast_t), typeof(identity), Type{Any}, Tuple{Base.OneTo{Int64}}, Float64, DataArrays.DataArray{Any, 1}, Int})
    precompile(Tuple{typeof(DataArrays.unsafe_ismissing), DataArrays.DataArray{Any, 1}, Tuple{Array{Any, 1}, Array{UInt64, 1}}, Int64})
    precompile(Tuple{getfield(DataArrays, Symbol("##mapreduce#30")), Bool, Bool, typeof(identity), typeof(identity), typeof(identity), DataArrays.DataArray{Float64, 1}})
    precompile(Tuple{typeof(DataArrays.unsafe_ismissing), DataArrays.DataArray{Any, 3}, Tuple{Array{Any, 3}, Array{UInt64, 1}}, Int64})
    precompile(Tuple{typeof(DataArrays.unsafe_ismissing), DataArrays.DataArray{Float64, 3}, Tuple{Array{Float64, 3}, Array{UInt64, 1}}, Int64})
    precompile(Tuple{typeof(DataArrays.unsafe_dasetindex!), DataArrays.DataArray{Any, 1}, Tuple{Array{Any, 1}, Array{UInt64, 1}}, Float64, Int64})
    precompile(Tuple{typeof(DataArrays.broadcast_t), typeof(identity), Type{Union{Float64, Missings.Missing}}, Tuple{Base.OneTo{Int64}}, DataArrays.DataArray{Float64, 1}, DataArrays.DataArray{Float64, 1}, DataArrays.DataArray{Float64, 1}})
    precompile(Tuple{typeof(DataArrays.unsafe_dasetindex!), DataArrays.DataArray{Any, 3}, Tuple{Array{Any, 3}, Array{UInt64, 1}}, Float64, Int64})
    precompile(Tuple{typeof(DataArrays.finduniques), DataArrays.DataArray{Float64, 1}})
    precompile(Tuple{typeof(DataArrays.unsafe_dasetindex!), Array{Any, 1}, Array{UInt64, 1}, Float64, Int64})
    precompile(Tuple{typeof(DataArrays.unsafe_bitsettrue!), Array{UInt64, 1}, Int64})
    precompile(Tuple{typeof(DataArrays.unsafe_dasetindex!), DataArrays.DataArray{Any, 2}, Tuple{Array{Any, 2}, Array{UInt64, 1}}, Float64, Int64})
    precompile(Tuple{typeof(DataArrays.unsafe_dasetindex!), Array{Any, 2}, Array{UInt64, 1}, Float64, Int64})
    precompile(Tuple{typeof(DataArrays.unsafe_bitsetfalse!), Array{UInt64, 1}, Int64})
    precompile(Tuple{typeof(DataArrays.dasort!), DataArrays.DataArray{Float64, 1}, Base.Sort.MergeSortAlg, Base.Order.ForwardOrdering})
    precompile(Tuple{typeof(DataArrays.gen_na_conds), Symbol, Int64, Tuple{DataType, DataType}, Type{Int}})
    precompile(Tuple{typeof(DataArrays.gen_na_conds), Symbol, Int64, Tuple{DataType, DataType, DataType, DataType}, Type{Int}})
end
