function _precompile_()
    ccall(:jl_generating_output, Cint, ()) == 1 || return nothing
    precompile(Tuple{typeof(DataStructures.rehash!), DataStructures.OrderedDict{String, QpcrAnalysis.AmpStepRampOutput2Bjson}, Int64})
    precompile(Tuple{typeof(DataStructures._setindex!), DataStructures.OrderedDict{String, QpcrAnalysis.AmpStepRampOutput2Bjson}, QpcrAnalysis.AmpStepRampOutput2Bjson, String, Int64})
    precompile(Tuple{typeof(DataStructures.ht_keyindex), DataStructures.OrderedDict{UInt8, Any}, Int64, Bool})
    precompile(Tuple{typeof(DataStructures.rehash!), DataStructures.OrderedDict{Symbol, Any}, Int64})
    precompile(Tuple{typeof(DataStructures._setindex!), DataStructures.OrderedDict{String, Any}, Tuple{Int64, Bool}, String, Int64})
    precompile(Tuple{typeof(DataStructures.ht_keyindex2), DataStructures.OrderedDict{Any, Any}, String})
    precompile(Tuple{typeof(DataStructures.rehash!), DataStructures.OrderedDict{String, Array{String, 1}}, Int64})
    precompile(Tuple{typeof(DataStructures._setindex!), DataStructures.OrderedDict{String, Any}, Tuple{Float64, Bool}, String, Int64})
    precompile(Tuple{typeof(DataStructures._setindex!), DataStructures.OrderedDict{String, Any}, Float64, String, Int64})
    precompile(Tuple{typeof(DataStructures.rehash!), DataStructures.OrderedDict{String, Any}, Int64})
    precompile(Tuple{typeof(DataStructures.rehash!), DataStructures.OrderedDict{UInt8, Any}, Int64})
    precompile(Tuple{typeof(DataStructures._setindex!), DataStructures.OrderedDict{String, Any}, Bool, String, Int64})
    precompile(Tuple{typeof(DataStructures.rehash!), DataStructures.OrderedDict{String, Void}, Int64})
    precompile(Tuple{typeof(DataStructures._setindex!), DataStructures.OrderedDict{String, Any}, String, String, Int64})
    precompile(Tuple{typeof(DataStructures.ht_keyindex), DataStructures.OrderedDict{Any, Any}, Symbol, Bool})
    precompile(Tuple{typeof(DataStructures._setindex!), DataStructures.OrderedDict{Any, Any}, Bool, String, Int64})
    precompile(Tuple{typeof(DataStructures.ht_keyindex), DataStructures.OrderedDict{String, Array{Any, 1}}, String, Bool})
    precompile(Tuple{typeof(DataStructures._setindex!), DataStructures.OrderedDict{String, Any}, DataArrays.DataArray{Float64, 1}, String, Int64})
    precompile(Tuple{typeof(DataStructures._setindex!), DataStructures.OrderedDict{Symbol, Any}, Int64, Symbol, Int64})
    precompile(Tuple{typeof(DataStructures._setindex!), DataStructures.OrderedDict{String, Array{Any, 1}}, Array{Any, 1}, String, Int64})
    precompile(Tuple{typeof(DataStructures._tablesz), Int64})
    precompile(Tuple{typeof(DataStructures._find_root_impl!), Array{Int64, 1}, Int64})
    precompile(Tuple{typeof(DataStructures.rehash!), DataStructures.OrderedDict{Any, Any}, Int64})
    precompile(Tuple{typeof(DataStructures.rehash!), DataStructures.OrderedDict{String, Array{Any, 1}}, Int64})
    precompile(Tuple{typeof(DataStructures._setindex!), DataStructures.OrderedDict{String, Any}, Array{DataStructures.OrderedDict{String, Any}, 1}, String, Int64})
    precompile(Tuple{typeof(DataStructures._setindex!), DataStructures.OrderedDict{String, Any}, Array{Float64, 1}, String, Int64})
    precompile(Tuple{typeof(DataStructures.ht_keyindex2), DataStructures.OrderedDict{Any, Any}, Symbol})
    precompile(Tuple{typeof(DataStructures._setindex!), DataStructures.OrderedDict{String, Any}, Array{DataStructures.OrderedDict{K, V} where V where K, 1}, String, Int64})
    precompile(Tuple{typeof(DataStructures.root_union!), DataStructures.IntDisjointSets, Int64, Int64})
    precompile(Tuple{typeof(DataStructures.ht_keyindex), DataStructures.OrderedDict{String, DataStructures.OrderedDict{Int64, Array{Float64, 1}}}, String, Bool})
    precompile(Tuple{typeof(DataStructures._setindex!), DataStructures.OrderedDict{String, Any}, Array{Any, 1}, String, Int64})
    precompile(Tuple{typeof(DataStructures._setindex!), DataStructures.OrderedDict{String, Any}, DataStructures.OrderedDict{String, Any}, String, Int64})
    precompile(Tuple{typeof(DataStructures.ht_keyindex2), DataStructures.OrderedDict{UInt8, Any}, UInt8})
    precompile(Tuple{typeof(DataStructures.rehash!), DataStructures.OrderedDict{Int64, Array{DataStructures.OrderedDict{String, Any}, 1}}, Int64})
    precompile(Tuple{typeof(DataStructures.ht_keyindex2), DataStructures.OrderedDict{String, Array{String, 1}}, String})
    precompile(Tuple{typeof(DataStructures.rehash!), DataStructures.OrderedDict{Int64, Array{Float64, 1}}, Int64})
    precompile(Tuple{typeof(DataStructures.rehash!), DataStructures.OrderedDict{Int64, DataArrays.DataArray{Any, 2}}, Int64})
    precompile(Tuple{typeof(DataStructures.ht_keyindex), DataStructures.OrderedDict{String, Float64}, String, Bool})
    precompile(Tuple{typeof(DataStructures.rehash!), DataStructures.OrderedDict{Base.Set{Array{Float64, 1}}, QpcrAnalysis.UniqCombinCenters}, Int64})
    precompile(Tuple{typeof(DataStructures._setindex!), DataStructures.OrderedDict{Base.Set{Array{AbstractFloat, 1}}, QpcrAnalysis.UniqCombinCenters}, QpcrAnalysis.UniqCombinCenters, Base.Set{Array{AbstractFloat, 1}}, Int64})
    precompile(Tuple{typeof(DataStructures.ht_keyindex), DataStructures.OrderedDict{Any, Any}, String, Bool})
    precompile(Tuple{typeof(DataStructures.rehash!), DataStructures.OrderedDict{String, QpcrAnalysis.AssignGenosResult}, Int64})
    precompile(Tuple{typeof(DataStructures.ht_keyindex2), DataStructures.OrderedDict{Base.Set{Array{AbstractFloat, 1}}, QpcrAnalysis.UniqCombinCenters}, Base.Set{Array{AbstractFloat, 1}}})
    precompile(Tuple{typeof(DataStructures.rehash!), DataStructures.OrderedDict{String, Array{Float64, 2}}, Int64})
    precompile(Tuple{typeof(DataStructures.rehash!), DataStructures.OrderedDict{String, Float64}, Int64})
    precompile(Tuple{typeof(DataStructures._setindex!), DataStructures.OrderedDict{Any, Any}, Array{Any, 1}, Symbol, Int64})
    precompile(Tuple{typeof(DataStructures.rehash!), DataStructures.OrderedDict{String, Array{Int64, 2}}, Int64})
    precompile(Tuple{typeof(DataStructures.rehash!), DataStructures.OrderedDict{String, Array{Bool, 2}}, Int64})
    precompile(Tuple{typeof(DataStructures.rehash!), DataStructures.OrderedDict{Symbol, Ipopt.IpoptSolver}, Int64})
    precompile(Tuple{typeof(DataStructures.rehash!), DataStructures.OrderedDict{String, DataStructures.OrderedDict{UInt8, Any}}, Int64})
    precompile(Tuple{typeof(DataStructures._setindex!), DataStructures.OrderedDict{Symbol, Any}, Float64, Symbol, Int64})
    precompile(Tuple{typeof(DataStructures.rehash!), DataStructures.OrderedDict{String, DataStructures.OrderedDict{Int64, Array{Float64, 1}}}, Int64})
    precompile(Tuple{typeof(DataStructures.rehash!), DataStructures.OrderedDict{String, AbstractFloat}, Int64})
    precompile(Tuple{typeof(DataStructures.rehash!), DataStructures.OrderedDict{Base.Set{Array{AbstractFloat, 1}}, QpcrAnalysis.UniqCombinCenters}, Int64})
    precompile(Tuple{typeof(DataStructures.ht_keyindex), DataStructures.OrderedDict{UInt8, Any}, UInt8, Bool})
    precompile(Tuple{typeof(DataStructures.ht_keyindex), DataStructures.OrderedDict{String, Function}, String, Bool})
    precompile(Tuple{typeof(DataStructures._setindex!), DataStructures.OrderedDict{String, DataStructures.OrderedDict{Int64, Array{Float64, 1}}}, DataStructures.OrderedDict{Int64, Array{Float64, 1}}, String, Int64})
    precompile(Tuple{typeof(DataStructures.ht_keyindex), DataStructures.OrderedDict{String, Any}, String, Bool})
    precompile(Tuple{typeof(DataStructures._setindex!), DataStructures.OrderedDict{String, Array{String, 1}}, Array{String, 1}, String, Int64})
    precompile(Tuple{typeof(DataStructures.ht_keyindex), DataStructures.OrderedDict{String, Array{Int64, 2}}, String, Bool})
    precompile(Tuple{typeof(DataStructures.ht_keyindex), DataStructures.OrderedDict{String, DataType}, String, Bool})
    precompile(Tuple{typeof(DataStructures._setindex!), DataStructures.OrderedDict{String, Float64}, Float64, String, Int64})
    precompile(Tuple{typeof(DataStructures._setindex!), DataStructures.OrderedDict{String, Any}, Int64, String, Int64})
    precompile(Tuple{typeof(DataStructures._setindex!), DataStructures.OrderedDict{String, Void}, Void, String, Int64})
    precompile(Tuple{typeof(DataStructures._setindex!), DataStructures.OrderedDict{Base.Set{Array{Float64, 1}}, QpcrAnalysis.UniqCombinCenters}, QpcrAnalysis.UniqCombinCenters, Base.Set{Array{Float64, 1}}, Int64})
    precompile(Tuple{typeof(DataStructures._setindex!), DataStructures.OrderedDict{Int64, DataArrays.DataArray{Any, 2}}, DataArrays.DataArray{Any, 2}, Int64, Int64})
    precompile(Tuple{typeof(DataStructures._setindex!), DataStructures.OrderedDict{String, Array{Int64, 2}}, Array{Int64, 2}, String, Int64})
    precompile(Tuple{typeof(DataStructures._setindex!), DataStructures.OrderedDict{Symbol, Ipopt.IpoptSolver}, Ipopt.IpoptSolver, Symbol, Int64})
    precompile(Tuple{typeof(DataStructures._setindex!), DataStructures.OrderedDict{Int64, Array{DataStructures.OrderedDict{String, Any}, 1}}, Array{DataStructures.OrderedDict{String, Any}, 1}, Int64, Int64})
    precompile(Tuple{typeof(DataStructures._setindex!), DataStructures.OrderedDict{String, Array{Bool, 2}}, Array{Bool, 2}, String, Int64})
    precompile(Tuple{typeof(DataStructures._setindex!), DataStructures.OrderedDict{String, Array{Float64, 2}}, Array{Float64, 2}, String, Int64})
    precompile(Tuple{typeof(DataStructures._setindex!), DataStructures.OrderedDict{String, QpcrAnalysis.AssignGenosResult}, QpcrAnalysis.AssignGenosResult, String, Int64})
    precompile(Tuple{typeof(DataStructures._setindex!), DataStructures.OrderedDict{String, DataStructures.OrderedDict{UInt8, Any}}, DataStructures.OrderedDict{UInt8, Any}, String, Int64})
    precompile(Tuple{typeof(DataStructures._setindex!), DataStructures.OrderedDict{UInt8, Any}, Array{Any, 1}, UInt8, Int64})
    precompile(Tuple{typeof(DataStructures.ht_keyindex), DataStructures.OrderedDict{Int64, Array{Float64, 1}}, Int64, Bool})
    precompile(Tuple{typeof(DataStructures._setindex!), DataStructures.OrderedDict{Int64, Array{Float64, 1}}, Array{Float64, 1}, Int64, Int64})
    precompile(Tuple{typeof(DataStructures.ht_keyindex), DataStructures.OrderedDict{String, DataStructures.OrderedDict{UInt8, Any}}, String, Bool})
    precompile(Tuple{typeof(DataStructures.ht_keyindex), DataStructures.OrderedDict{String, QpcrAnalysis.SFCModelDef}, String, Bool})
    precompile(Tuple{typeof(DataStructures.ht_keyindex), DataStructures.OrderedDict{Symbol, Ipopt.IpoptSolver}, Symbol, Bool})
    precompile(Tuple{typeof(DataStructures.ht_keyindex2), DataStructures.OrderedDict{String, QpcrAnalysis.AmpStepRampOutput2Bjson}, String})
    precompile(Tuple{typeof(DataStructures.rehash!), DataStructures.OrderedDict{Array{Int64, 1}, Array{Int64, 1}}, Int64})
    precompile(Tuple{typeof(DataStructures.ht_keyindex2), DataStructures.OrderedDict{String, Array{Any, 1}}, String})
    precompile(Tuple{typeof(DataStructures.ht_keyindex), DataStructures.OrderedDict{Base.Set{Array{AbstractFloat, 1}}, QpcrAnalysis.UniqCombinCenters}, Base.Set{Array{Float64, 1}}, Bool})
    precompile(Tuple{typeof(DataStructures.ht_keyindex), DataStructures.OrderedDict{Base.Set{Array{Float64, 1}}, QpcrAnalysis.UniqCombinCenters}, Base.Set{Array{Float64, 1}}, Bool})
    precompile(Tuple{typeof(DataStructures.ht_keyindex2), DataStructures.OrderedDict{Symbol, Any}, Symbol})
    precompile(Tuple{typeof(DataStructures.ht_keyindex2), DataStructures.OrderedDict{Int64, DataArrays.DataArray{Any, 2}}, Int64})
    precompile(Tuple{typeof(DataStructures.ht_keyindex2), DataStructures.OrderedDict{Int64, Array{DataStructures.OrderedDict{String, Any}, 1}}, Int64})
    precompile(Tuple{typeof(DataStructures.ht_keyindex2), DataStructures.OrderedDict{String, Any}, String})
    precompile(Tuple{typeof(DataStructures.find_root_impl!), Array{Int64, 1}, Int64})
    precompile(Tuple{typeof(DataStructures.ht_keyindex2), DataStructures.OrderedDict{Base.Set{Array{Float64, 1}}, QpcrAnalysis.UniqCombinCenters}, Base.Set{Array{Float64, 1}}})
    precompile(Tuple{typeof(DataStructures.ht_keyindex2), DataStructures.OrderedDict{String, Array{Float64, 2}}, String})
    precompile(Tuple{typeof(DataStructures.ht_keyindex2), DataStructures.OrderedDict{Int64, Array{Float64, 1}}, Int64})
    precompile(Tuple{typeof(DataStructures.ht_keyindex2), DataStructures.OrderedDict{String, Array{Int64, 2}}, String})
    precompile(Tuple{typeof(DataStructures.ht_keyindex2), DataStructures.OrderedDict{String, DataStructures.OrderedDict{Int64, Array{Float64, 1}}}, String})
    precompile(Tuple{typeof(DataStructures.ht_keyindex2), DataStructures.OrderedDict{String, Void}, String})
    precompile(Tuple{typeof(DataStructures.ht_keyindex2), DataStructures.OrderedDict{String, Array{Bool, 2}}, String})
    precompile(Tuple{typeof(DataStructures.ht_keyindex2), DataStructures.OrderedDict{String, QpcrAnalysis.AssignGenosResult}, String})
    precompile(Tuple{typeof(DataStructures.ht_keyindex2), DataStructures.OrderedDict{String, Float64}, String})
    precompile(Tuple{typeof(DataStructures.ht_keyindex2), DataStructures.OrderedDict{String, DataStructures.OrderedDict{UInt8, Any}}, String})
    precompile(Tuple{typeof(DataStructures.ht_keyindex2), DataStructures.OrderedDict{Symbol, Ipopt.IpoptSolver}, Symbol})
end
