function _precompile_()
    ccall(:jl_generating_output, Cint, ()) == 1 || return nothing
    precompile(Tuple{getfield(DataFrames, Symbol("#kw##groupby")), Array{Any, 1}, typeof(DataFrames.groupby), DataFrames.DataFrame, Array{Symbol, 1}})
    precompile(Tuple{typeof(DataFrames.add_names), DataFrames.Index, DataFrames.Index})
    precompile(Tuple{typeof(DataFrames.hashrows), DataFrames.DataFrame, Bool})
    precompile(Tuple{typeof(DataFrames.row_group_slots), Tuple{Array{Real, 1}}, Array{UInt64, 1}, Array{Bool, 1}, Array{Int64, 1}, Bool})
    precompile(Tuple{typeof(DataFrames.insert_single_column!), DataFrames.DataFrame, Array{QpcrAnalysis.GroupResultEle, 1}, Symbol})
    precompile(Tuple{getfield(DataFrames, Symbol("##35#37")), Base.Pair{Symbol, QpcrAnalysis.GroupResultEle}})
    precompile(Tuple{getfield(DataFrames, Symbol("##35#37")), Base.Pair{Symbol, Int64}})
    precompile(Tuple{getfield(DataFrames, Symbol("##35#37")), Base.Pair{Symbol, QpcrAnalysis.TargetResultEle}})
    precompile(Tuple{typeof(DataFrames.insert_single_column!), DataFrames.DataFrame, Array{Int64, 1}, Symbol})
    precompile(Tuple{getfield(DataFrames, Symbol("#kw##make_unique")), Array{Any, 1}, typeof(DataFrames.make_unique), Array{Symbol, 1}})
    precompile(Tuple{typeof(DataFrames.hashrows_col!), Array{UInt64, 1}, Array{Bool, 1}, Array{Real, 1}})
    precompile(Tuple{getfield(DataFrames, Symbol("##DataFrame#39")), Array{Any, 1}, Type{Int}})
    precompile(Tuple{getfield(DataFrames, Symbol("##36#38")), Base.Pair{Symbol, QpcrAnalysis.TargetResultEle}})
    precompile(Tuple{typeof(DataFrames._vcat), Array{DataFrames.DataFrame, 1}})
    precompile(Tuple{getfield(DataFrames, Symbol("##36#38")), Base.Pair{Symbol, Int64}})
    precompile(Tuple{getfield(DataFrames, Symbol("##36#38")), Base.Pair{Symbol, QpcrAnalysis.GroupResultEle}})
    precompile(Tuple{getfield(DataFrames, Symbol("##groupby#54")), Bool, Bool, typeof(identity), DataFrames.DataFrame, Array{Symbol, 1}})
    precompile(Tuple{getfield(DataFrames, Symbol("##40#41")), Tuple{Symbol, QpcrAnalysis.TargetResultEle}})
    precompile(Tuple{getfield(DataFrames, Symbol("##40#41")), Tuple{Symbol, QpcrAnalysis.GroupResultEle}})
    precompile(Tuple{getfield(DataFrames, Symbol("##40#41")), Tuple{Symbol, Array{Int64, 1}}})
    precompile(Tuple{getfield(DataFrames, Symbol("##make_unique#1")), Bool, typeof(identity), Array{Symbol, 1}})
    precompile(Tuple{getfield(DataFrames, Symbol("##40#41")), Tuple{Symbol, Int64}})
    precompile(Tuple{getfield(DataFrames, Symbol("##40#41")), Tuple{Symbol, Array{Real, 1}}})
    precompile(Tuple{getfield(DataFrames, Symbol("##36#38")), Base.Pair{Symbol, Array{AbstractFloat, 1}}})
    precompile(Tuple{getfield(DataFrames, Symbol("##40#41")), Tuple{Symbol, Array{AbstractFloat, 1}}})
    precompile(Tuple{getfield(DataFrames, Symbol("##35#37")), Base.Pair{Symbol, Array{Int64, 1}}})
    precompile(Tuple{typeof(DataFrames.group_rows), DataFrames.DataFrame, Bool})
    precompile(Tuple{getfield(DataFrames, Symbol("#kw##by")), Array{Any, 1}, typeof(DataFrames.by), DataFrames.DataFrame, Symbol, typeof(identity)})
    precompile(Tuple{typeof(DataFrames.hcat!), DataFrames.DataFrame, DataFrames.DataFrame})
    precompile(Tuple{getfield(DataFrames, Symbol("##35#37")), Base.Pair{Symbol, Array{Real, 1}}})
    precompile(Tuple{getfield(DataFrames, Symbol("##36#38")), Base.Pair{Symbol, Array{Real, 1}}})
    precompile(Tuple{getfield(DataFrames, Symbol("##35#37")), Base.Pair{Symbol, Array{AbstractFloat, 1}}})
    precompile(Tuple{getfield(DataFrames, Symbol("##36#38")), Base.Pair{Symbol, Array{Int64, 1}}})
    precompile(Tuple{typeof(DataFrames.insert_single_column!), DataFrames.DataFrame, Array{QpcrAnalysis.TargetResultEle, 1}, Symbol})
    precompile(Tuple{getfield(DataFrames, Symbol("#kw##groupby")), Array{Any, 1}, typeof(DataFrames.groupby), DataFrames.DataFrame, Symbol})
    precompile(Tuple{typeof(DataFrames.row_group_slots), DataFrames.DataFrame, Array{Int64, 1}, Bool})
    precompile(Tuple{typeof(DataFrames.combine), DataFrames.GroupApplied{DataFrames.DataFrame}})
end
